---
# tasks file for splunk_deployment_server
#- name: Create Splunk Directory
#  file:
#    path: /tmp/splunk #/etc/master-apps/
#    state: directory
#    owner: ansible
#    group: ansible
#    mode: 0755
- name: Deploy Apps from Github to Indexers
  git:
    repo: https://github.com/layamba25/my_ansible_projects.git #git@github.com:layamba25/my_ansible_projects.git
    dest: /tmp/test4 #/opt/splunk/etc/master-apps/
    force: yes

#- include_tasks: roles/splunk_common/tasks/enable_forwarding.yml

#- include_tasks: create_deployment_apps.yml
#  when:
#    - splunk.apps_location

#- include_tasks: generate_server_classes.yml

#- name: Reload deployment server
#  command: "{{ splunk.exec }} reload deploy-server -auth {{ splunk.admin_user }}:{{ splunk.password }} -timeout {{ retry_delay * retry_num }}"
#  become: yes
#  become_user: "{{ splunk.user }}"
#  register: reload_depserver
#  until: reload_depserver.rc == 0
#  changed_when: reload_depserver.rc == 0
#  retries: "{{ retry_num }}"
#  delay: "{{ retry_delay }}"
#  ignore_errors: yes
#  no_log: "{{ hide_password }}"

#- include_tasks: roles/splunk_common/tasks/check_for_required_restarts.yml

